---
- name: install updates
  yum:
    name: "*"
    state: latest
  ignore_errors: true

- name: install support packages
  yum: pkg={{ item }} state=present
  with_items:
    - ntp
    - vim
    - dhcp
    - wget
    - docker
    - python-pip
    - sshpass
    - iptables-services
    - libvirt
    - libvirt-client
    - libvirt-python
    - qemu-img
    - qemu-kvm
    - bridge-utils

- name: install docker-py
  pip:
    name: docker-py
    state: present
    extra_args: "--upgrade"

- name: create .ssh directory
  file:
    path: /root/.ssh/
    state: directory

- name: copy .ssh/config
  copy:
    src: config
    dest: /root/.ssh/config
    mode: 600

- name: disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: create directories for hanlon
  file:
    path: "{{ item }}"
    state: directory
    setype: svirt_sandbox_file_t
    recurse: true
  with_items:
    - /opt/hanlon
    - /opt/hanlon/image
    - /opt/deploy

- name: copy iptables config file
  copy:
    src: iptables
    dest: /etc/sysconfig/iptables

- name: start & enable services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker
    - iptables

- name: clone repos from git
  git:
    repo: "{{ item.repo }}"
    dest: "/root/{{ item.name }}"
    accept_hostkey: yes
  ignore_errors: true
  with_items:
    - { name: "wiley", repo: "git://github.com/csc/wiley" }
    - { name: "slimer", repo: "git://github.com/csc/slimer" }
    - { name: "ansible-scaleio", repo: "git://github.com/csc/ansible-scaleio" }
